name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
    
    - name: Backend Linting
      run: |
        cd backend
        echo "Linting check would run here"
        # npm run lint (Nous l'ajouterons plus tard)
    
    - name: Backend Tests
      run: |
        cd backend
        echo "Tests would run here"
        # npm test (Nous l'ajouterons plus tard)
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
    
    - name: Frontend Linting
      run: |
        cd frontend
        echo "Linting check would run here"
        # npm run lint (Nous l'ajouterons plus tard)
    
    - name: Frontend Tests
      run: |
        cd frontend
        echo "Tests would run here"
        # npm test (Nous l'ajouterons plus tard)

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Backend Docker Image
      run: |
        cd backend
        docker build -t trading-ai-backend:latest .
    
    - name: Build Frontend Docker Image
      run: |
        cd frontend
        docker build -t trading-ai-frontend:latest .
    
    - name: Test Docker Compose
      run: |
        docker-compose build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Simulation
      run: |
        echo "Deployment would happen here in a real scenario"
        echo "This will be configured to deploy to AWS when we have access"
