name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    
    - name: Run Tests in Docker
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml run backend npm test
        docker-compose -f docker-compose.yml run frontend npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.prod.yml build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Simulation
      run: |
        echo "En préparation pour le déploiement AWS ultérieur"
        echo "À ce stade, nous simulerons seulement le déploiement"