name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run Backend Tests
      run: |
        cd backend
        npm ci
        npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: |
        cd backend
        npm ci
        cd ../frontend
        npm ci
    
    - name: Build Project
      run: |
        cd backend
        npm run build
        cd ../frontend
        npm run build
    
    - name: Build Backend Docker Image
      run: |
        cd backend
        docker build -t trading-ai-backend:latest .
    
    - name: Build Frontend Docker Image
      run: |
        cd frontend
        docker build -t trading-ai-frontend:latest .
    
    - name: Test Docker Compose
      run: |
        docker-compose build

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Deploy Simulation
  #     run: |
  #       echo "Deployment would happen here in a real scenario"
  #       echo "This will be configured to deploy to AWS when we have access"
